import type { MerchantProduct, MerchantProductCategory } from '#shared/types/merchant'

/** See /Merchant feature/13. Product Categories.png and /19. All products list and availabilty.png. */
export const mockMerchantCategories: MerchantProductCategory[] = [
  { id: 'cat-electronics', name: 'Electronics', description: 'Electronics devices and gadgets', status: 'active', productCount: 120 },
  { id: 'cat-home-decor', name: 'Home Decor', description: 'Furnishings and decorative pieces', status: 'active', productCount: 46 },
  { id: 'cat-womens', name: "Women's", description: "Women's clothing and accessories", status: 'active', productCount: 84 },
  { id: 'cat-mens', name: "Men's", description: "Men's clothing and accessories", status: 'active', productCount: 61 },
  { id: 'cat-kiddies', name: 'Kiddies', description: 'Toys, clothing and essentials for kids', status: 'active', productCount: 33 },
  { id: 'cat-office', name: 'Office Appliances', description: 'Printers, desk tech and office gear', status: 'inactive', productCount: 89 },
]

export const mockMerchantProducts: MerchantProduct[] = [
  {
    id: 'mp-smart-watch-series-9',
    name: 'Smart Watch Series 9',
    sku: 'RRR-18299',
    barcode: '798588969094948',
    category: 'Electronics',
    subcategory: 'Wristwatch',
    brand: 'ReStockr',
    description: 'Series 9 smart watch with an always-on display and all-day fitness tracking.',
    images: [{ url: '/images/products/realme-buds-air.jpg', alt: 'Smart Watch Series 9' }],
    regularPrice: 45000,
    salePrice: 35000,
    costPrice: 25000,
    quantityInStock: 120,
    lowStockThreshold: 20,
    allowBackorders: false,
    trackInventory: true,
    status: 'active',
    availability: 'in-stock',
    visibility: 'everyone',
  },
  {
    id: 'mp-wireless-earbuds',
    name: 'True Wireless Earbuds',
    sku: 'RRR-18300',
    category: 'Electronics',
    subcategory: 'Audio',
    brand: 'ReStockr',
    description: 'TWS earbuds with an LED battery-level charging case.',
    images: [{ url: '/images/products/wireless-earbuds.jpg', alt: 'True Wireless Earbuds' }],
    regularPrice: 18000,
    quantityInStock: 64,
    lowStockThreshold: 15,
    allowBackorders: false,
    trackInventory: true,
    status: 'active',
    availability: 'in-stock',
    visibility: 'everyone',
  },
  {
    id: 'mp-bluetooth-speaker',
    name: 'Portable Bluetooth Speaker',
    sku: 'RRR-18301',
    category: 'Electronics',
    subcategory: 'Audio',
    brand: 'ReStockr',
    description: 'Pill-shaped speaker with a fabric finish and deep bass.',
    images: [{ url: '/images/products/bluetooth-speaker.jpg', alt: 'Portable Bluetooth Speaker' }],
    regularPrice: 22000,
    quantityInStock: 41,
    lowStockThreshold: 10,
    allowBackorders: true,
    trackInventory: true,
    status: 'active',
    availability: 'in-stock',
    visibility: 'everyone',
  },
  {
    id: 'mp-camera',
    name: 'Mirrorless Camera',
    sku: 'RRR-18302',
    category: 'Electronics',
    subcategory: 'Cameras',
    brand: 'ReStockr',
    description: 'Full-frame mirrorless camera with a standard zoom lens.',
    images: [{ url: '/images/products/mirrorless-camera.jpg', alt: 'Mirrorless Camera' }],
    regularPrice: 850000,
    quantityInStock: 8,
    lowStockThreshold: 3,
    allowBackorders: false,
    trackInventory: true,
    status: 'active',
    availability: 'in-stock',
    visibility: 'everyone',
  },
  {
    id: 'mp-sunglasses',
    name: 'Matte Aviator Sunglasses',
    sku: 'RRR-18303',
    category: "Men's",
    brand: 'ReStockr',
    description: 'Oversized matte-black frame, UV400 lenses.',
    images: [{ url: '/images/products/matte-aviator-sunglasses.jpg', alt: 'Matte Aviator Sunglasses' }],
    regularPrice: 12000,
    quantityInStock: 0,
    lowStockThreshold: 10,
    allowBackorders: false,
    trackInventory: true,
    status: 'inactive',
    availability: 'out-of-stock',
    visibility: 'hidden',
  },
]
