// @ts-check
// `.nuxt/eslint.config.mjs` is generated by the @nuxt/eslint module (via
// `nuxt prepare`) with rules derived from this project's actual Nuxt config
// — extending it here instead of hand-rolling `createConfigForNuxt` keeps
// lint rules in sync with whatever modules/aliases are actually enabled.
import withNuxt from './.nuxt/eslint.config.mjs'
import prettier from 'eslint-config-prettier'

export default withNuxt(
  prettier,
  {
    rules: {
      // Single-word component names (e.g. `Header.vue` -> <Header>) are
      // fine here: the naming convention is directory-scoped auto-import
      // prefixes (components/product/Gallery.vue -> <ProductGallery>).
      'vue/multi-word-component-names': 'off',
    },
  },
  {
    ignores: ['playwright-report/**', 'test-results/**'],
  },
)
